version: '3.5'

networks:
  nginx-php-mysql-ws:

services:
  mailer:
    image: schickling/mailcatcher
    ports: [ "1025", "1080" ]

  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container-ws
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - .:/var/www/project
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
      - mysql-service
    networks:
      - nginx-php-mysql-ws

  php-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php-container-ws
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/project
    networks:
      - nginx-php-mysql-ws

  mysql-service:
    image: mysql:8
    container_name: mysql-container-ws
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - nginx-php-mysql-ws